{
 "title": "OpenVPN Server",
 "description": "OpenVPN Server status using Prometheus and OpenVPN exporter ",
 "tags": [ "openvpn" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openvpn_server_connected_clients"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "openvpn_up{job=\"openvpn-metrics\"}"
    }
   ]
  },
  {
   "title": "Clients Connected",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Clients" }
   ],
   "targets": [
    {
     "expr": "sum(openvpn_server_connected_clients)",
     "legendFormat": "Connected OpenVPN Clients"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(openvpn_server_client_sent_bytes_total[1d]))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(openvpn_server_connected_clients{instance=~\"[0-9].+:[0-9]{0,}\"}) or absent(count(openvpn_server_connected_clients{instance=~\"[0-9].+:[0-9]{0,}\"}))-1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "time()-openvpn_status_update_time_seconds{job=\"openvpn-metrics\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(openvpn_server_client_received_bytes_total[1d]))"
    }
   ]
  },
  {
   "title": "Current OpenVPN Clients",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sort_desc(sum(label_replace(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}, \"connection_time\", \"${1}000\", \"connection_time\", \"(.*)\"))by(common_name, connection_time, virtual_address))"
    },
    {
     "expr": "sum(label_replace(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}, \"connection_time\", \"${1}000\", \"connection_time\", \"(.*)\"))by(common_name, connection_time, virtual_address)"
    }
   ]
  },
  {
   "title": "Top Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(increase(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[1d])+increase(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}[1d]))by(common_name))",
     "legendFormat": "{{ common_name }}"
    }
   ]
  }
 ]
}